OPSAPS-26038. Conditionalize 'roles' argument.
Tests running against older CM versions had the following
error:
    test_support_bundle45 fails with error: Unrecognized property: 'roles' (error 400)

As it turns out, we have the capability to set an API
version when using the python client, and the client
should take care of things like this, so I've done so.

To test this, I ran:

  $ cp ~/src/cm_api/python/src/cm_api/endpoints/cms.py ./target/env/lib/python2.7/site-packages/cm_api/endpoints/cms.py
  $ systest.py --agents="cdh5+parcels@nightly53-{1..4}.ent.cloudera.com" run_tests -n "test_support_bundle:SupportBundleTests.test_support_bundle_45" --disable-pre-validations  --version cm53

Before my change (that I manually cherrypicked in the first hand):

        ApiException: Unrecognized property: 'roles' (error 400)

        ----------------------------------------------------------------------
        Ran 1 test in 0.499s

        FAILED (errors=1)
        False

After:

    ***********************************************************************
    * End test_support_bundle_45 (test_support_bundle.SupportBundleTests) *
    ***********************************************************************

    ----------------------------------------------------------------------
    Ran 1 test in 128.929s

I also tested against nightly (5.5) to make sure this didn't regress.
It passed.

    $./systest.py --agents="cdh5+parcels@nightly-{1..4}.ent.cloudera.com" run_tests -n "test_support_bundle:SupportBundleTests.test_support_bundle_45"
    --disable-pre-validations

(cherry picked from commit e58b3ccf2a5b63bf42460fde1f9b1c2e596bf440)