[cm_api] Fix cluster rename
_put masked the super _put and would result in something like:
TypeError: _put() got an unexpected keyword argument 'data'

Also after the display name change, the rename has no effect since it's
still updating "name". Fixed to be "displayName", but not sure if the
binding if always for latest version or does it need to handle older
versions?