[cm_api] Expose cluster full version and method to update
Verified that a rejected update results in something like:
cm_api.api_client.ApiException: com.cloudera.server.cmf.VersionChangeException: Version change to CDH 4.1.2 would lose access to services [sqoop3] and/or roles [] (error 400)